package Models;

import java.sql.Timestamp;

// Represents a meal plan generated by a nutritionist
public class NutritionistProgram {
    private int id;
    private int userId;
    private String goal;
    private String dietType;
    private String allergies;
    private String activityLevel;
    private String name;
    private String gender;
    private int age;
    private int heightCm;
    private int weightKg;
    private String mealFrequency;
    private String cuisinePreference;
    private String mealPlan;
    private Timestamp createdAt;
    private boolean editMode; // Indicates if the program is in edit mode

    // Constructor to initialize all fields
    public NutritionistProgram(int id, int userId, String goal, String dietType, String allergies,
                               String activityLevel, String name, String gender, int age, int heightCm, int weightKg,
                               String mealFrequency, String cuisinePreference, String mealPlan, Timestamp createdAt) {
        this.id = id;
        this.userId = userId;
        this.goal = goal;
        this.dietType = dietType;
        this.allergies = allergies;
        this.activityLevel = activityLevel;
        this.name =name;
        this.gender = gender;
        this.age = age;
        this.heightCm = heightCm;
        this.weightKg = weightKg;
        this.mealFrequency = mealFrequency;
        this.cuisinePreference = cuisinePreference;
        this.mealPlan = mealPlan;
        this.createdAt = createdAt;
        this.editMode = false;
    }

    // Getters
    public int getId() { return id; }
    public int getUserId() { return userId; }
    public String getGoal() { return goal; }
    public String getDietType() { return dietType; }
    public String getAllergies() { return allergies; }
    public String getActivityLevel() { return activityLevel; }
    public String getName() { return name;}
    public String getGender() {return gender;}
    public int getAge() { return age; }
    public int getHeightCm() { return heightCm; }
    public int getWeightKg() { return weightKg; }
    public String getMealFrequency() { return mealFrequency; }
    public String getCuisinePreference() { return cuisinePreference; }
    public String getMealPlan() { return mealPlan; }
    public Timestamp getCreatedAt() { return createdAt; }
    public boolean isEditMode() { return editMode; }

    // Setters
    public void setId(int id) { this.id = id; }
    public void setUserId(int userId) { this.userId = userId; }
    public void setGoal(String goal) { this.goal = goal; }
    public void setDietType(String dietType) { this.dietType = dietType; }
    public void setAllergies(String allergies) { this.allergies = allergies; }
    public void setActivityLevel(String activityLevel) { this.activityLevel = activityLevel; }
    public void setName(String name) {this.name = name;}
    public void setGender(String gender) {this.gender = gender;}
    public void setAge(int age) { this.age = age; }
    public void setHeightCm(int heightCm) { this.heightCm = heightCm; }
    public void setWeightKg(int weightKg) { this.weightKg = weightKg; }
    public void setMealFrequency(String mealFrequency) { this.mealFrequency = mealFrequency; }
    public void setCuisinePreference(String cuisinePreference) { this.cuisinePreference = cuisinePreference; }
    public void setMealPlan(String mealPlan) { this.mealPlan = mealPlan; }
    public void setCreatedAt(Timestamp createdAt) { this.createdAt = createdAt; }
    public void setEditMode(boolean editMode) { this.editMode = editMode; }
}
